### ISSUE TITLE
[Core] - Rogue - Subtlety - Shadow Dance

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#1053]
**Links:**
https://www.wowhead.com/spell=185313/shadow-dance

**What is happening:**
When used, it uses the normal casting bar for the entire duration.

**What should happen:**
It should swap to the stealth casting bar for the entire duration.

**Comment by ShikoSCS** [comment]
Fixed, please test it

**Comment by antonioyu0505** [comment]
Not working yet.

**Comment by ShikoSCS** [comment]
Excuse me, please try again once the fix is announced in the changelog -------- Mensaje original --------Asunto: Re: [GuabinaCore/WoWKoi] [Core] - Rogue - Subtlety - Shadow Dance (#1053)De: antonioyu0505 Para: GuabinaCore/WoWKoi CC: ShikoSCS ,State change 
Not working yet.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/GuabinaCore/WoWKoi/issues/1053#issuecomment-628302390",
"url": "https://github.com/GuabinaCore/WoWKoi/issues/1053#issuecomment-628302390",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
