### ISSUE TITLE
[Arthas] - Quest The Warden's Game 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1207]
**Links:**

https://www.wowhead.com/quest=27885/the-wardens-game

**What is happening:**
At some point the figure stack at one position for no reason.
Its Rip
https://streamable.com/ipfai0

**What should happen:**

If u abound the quest it supposes to reset the figures.

**Comment by GhostySimon** [comment]
Same problem for me as well.

**Comment by LKArthas** [comment]
Did you get away from it and try to do it again????

**Comment by NightwindOI** [comment]
So if u abound the quest--->run away and take it again they reset. So after 20 tries, I completed it.
If u ''right click'' on the figures they bug out and stack on each other. If u ''move'' them with a left-click it works. Have no f*king idea why and how :D

**Comment by Clangeddin** [comment]
Left click does not work for me, they start stacking on top of each other anyway.

**Comment by Clangeddin** [comment]
Ok, I figured it out, the stacking happens if you click too fast. Wait 5 seconds or so before clicking on another statue and it is fine. I did it with left click, but I think that right click should be fine as well, as long as you take it slow and wait. Don't rush or they will begin stacking on top of each other.
