### ISSUE TITLE
Leveling experience

### ISSUE THREAD

**Issue by taktrix** [GuabinaCore/WoWKoi#1220]
There's a thing that I told retail WoW devs to do for years before they finally rolled around to doing it, and it made the game experience 100% better. It's called progressive leveling. Here's how it works. Instead of zones having mobs and bosses that are specific levels what they have instead is called "relative levels". Now what relative levels are is every mob, boss and NPC in the wild will have a level that is relative directly to your level. So if you walk around Durotar at level 1 they will all be level 1, but if you walk around it at level 60 they will all be level 60. 

There are a couple of reasons why this works and is much better. First, Retail WoW had a major issue which they are now resolving, over the span of multiple xpacs they keep having to scale levels up and down and it keeps breaking the last xpac. As a result in the newest xpac they are releasing now (shadowlands) they have finally resolved this issue by scaling the entire world down to level 60 cap and having relative scaling on everything. So my suggestion is you do that right now before you start making everything else. Apply relative leveling and then set the cap at level 60 for the entire game. That way no matter what xpac comes later on you won't have to mess with the scaling at all.

Another reason why relative scaling works much better is because of the things you can do in a party, lets say you party with a group of people that are not quite your level but close, you're level 56 they're level 48, 49, and 52. Relative leveling will set all the mobs on their screen to each individual persons level and the damage/healing they get will all be relative to their level. You might be wondering "well how does that work?" 

Here's how it works. Instead of applying flat numbers(you get hit for 99 dmg, 120 dmg) you apply a percentage calculator. Like (you hit the mob for 1.5% dmg or heal for 6% health). That way it doesn't matter who is at what level because all the damage and healing is completely relative to their level and the same across everyones screen for them.

**Comment by Serithul** [comment]
Zone scale exactly to your level on the server. On 7.3.5 on the starting zones scaled till level 20 (source: https://wow.gamepedia.com/Zone_scaling). About the damage scaling, it's worked on with a lot of fixes lately. Level 60 for all xpac is not blizzlike, as in 7.3.5 the level cap is 110 and zones on each xpac scale from the starting level of the xpac till the level cap of it.

**Comment by taktrix** [comment]
You're right if the only xpac you want to finish on is 7.3.5, however in the next xpac that they're releasing they're level squishing everything to 1-60 so it would actually make it 100% blizzlike.

**Comment by Serithul** [comment]
Blizzlike means making it the patch/xpac as blizz made that patch, not as blizz retail server is right now/will be. Meaning if they make the server cap at level 60 (which needs a whole lot of new scripting since patch 7.x scripting is almost fully different than SL patch, meaning it's almost impossible to do since SL hasn't launched yet and there is no way of knowing how Blizz changed the questlines, scaling, spells, etc.) it won't be blizzlike.

**Comment by taktrix** [comment]
They are rescripting the whole game. That's the only way they could squish it all down. Which is the right move, I've been telling them for over a decade they need to do it, it will solve a lot of the bugs and issues with the way people progress though the game. And if done correctly it will make all the old and new content viable again.

**Comment by Serithul** [comment]
Blizzard is able to do it because it's their program and they have a quite a lot of people working for it. It's not the same with the private servers. A team behind a private server isn't even 1/10 of Blizzs'. It would take them years to rescript the whole server from vanilla till legion in order to do what Blizz does in SL. Which also beats the point of playing on a Legion private server. The leveling experience on Legion is really good, no problems arise especially since the zones scale up to your level.

**Comment by taktrix** [comment]
You're right they have a large team, but the program is only partially theirs, it was fully theirs but they fired and had so many devs of the original team quit that the only way they got that part back is because of some very good private server devs were kind enough to give them the scripting they had. That's actually how they recreated classic WoW.  

Hey if you want to keep this server a legion server forever more power to you. But let me ask you this, why would anyone play this server compared to any other private legion server? I mean that genuinely, the other servers are literally years ahead in time in. Which means even for all the bugs they currently have they will more than make up for them in content. So if you were a new player coming to this server what would be the draw? Because for my 2 cents if you make this server blizzlike at the rate it's going, you'll have it up to snuff in years, by which point all the other servers that already have multiple thousands of players will already have fixed the issues they once had and be fully stocked.

**Comment by Serithul** [comment]
I would prefer playing on this Legion server which offers quality than playing on any other Legion server atm which only offers semi-scripted end game content and only that, no other content before is even mediocre-ly scripted. Literally all legion server out the right now are the worst private servers ever to exist, they compete with each other on who is the least worst out of all. There have been a lot of private server on Legion content for a couple of years now, namely Freakz and Firestorm, both of them instead becoming better they only become worse with time, they fix 1 thing while 10 others get messed up and especially Freakz, prefers to mute people that complain about the server becoming worse and worse than fixing it properly instead of selling BiS gear for 100+ $. And these are facts known to most players playing Legion atm, but because there is no alternative Legion server which is good, tolerate their badness.

The rate of fixing you say this server has, is quite fast. And once the problems are solved all other expansions will be scripted much faster since most core wide issues, like AI behavior, classes, even triggers, etc, will have been fixed. The amount of content Vanilla has is almost worth 2-2,5 expansions.

**Comment by taktrix** [comment]
I agree with you and if this server offered quality I would be 100% here instead of anywhere else. But this server is nowhere near finished yet, it's just getting started. And for all the stuff that both those servers did wrong(and it is a lot) they have a ton more that they actually did correctly. Now Freakz right now is in a fucking terrible state, however that's only because they just upgraded from 7.2.5 to 7.3.5 which was a mistake, because they didn't nearly fix half of the shit that was wrong with that server before the upgrade and after the upgrade the broke the remainder. So you're right in the sense that right now there is no "good" legion server. 

And I like you would love to play a good legion server, however one doesn't exist yet, because this server is all but in its infancy. And you can talk about how much better it will be however it's not there yet, not even close. So at the moment what you're offering is the POTENTIAL to be better, which means less than nothing to players.

**Comment by Velthur-bot-3000** [comment]
Less then nothing to you? you mean?

**Comment by taktrix** [comment]
No, less than nothing to players, you think it's a coincidence that this server has a population of sub 100 instead of 10,000? Players don't give a shit about potential, they give a shit about gameplay. If your server doesn't have the gameplay all the potential in the world won't make up for it.

**Comment by Serithul** [comment]
You see it less than nothing. There are actually many players coming in everyday eager to play on this server because of the quality it offers even on the lowest expansion, wanting to help make the server the best Legion out there. And it will be done, whether one can see it or not. It's not just a potential that many of us have seen in here, especially the ones playing from almost the start of the server. From the launch till now, it has been almost 2.5 months and the state that the server is in is incredibly awesome, with fixes coming in on a DAILY basis, whereas other servers fix stuff once a month while 10 other stuff, coincidentally or not, break.

**Comment by taktrix** [comment]
The quality it offers right now is very VERY broken. I'm in the intro city I've already found and reported around 18 bugs. So I'm not sure what quality you're talking about. Because if you're going to sit here and tell me this server is less buggy than any of the other ones we're going to have to agree to disagree. Especially since I saw the battle pet scripting is cut and paste from another server that I played on. Down to the double atk/capture animation at the end of the fight.

**Comment by Serithul** [comment]
It's actually the other way around mate. You haven't seen the scripting of the zones since you are in the intro city, so saying that the quality is really really broken is an understatement. The battle pet system isn't ready yet, none said it is ready and it's not stated anywhere that it is ready, it needs testing and it will get fixed when other issues that are more important are fixed. This server is 2.5 months old, it's almost natural to be this "buggy" unlike other legion servers who have been around for years. I can't say whether or not this server is less buggy than other legion ones since we are locked out from all content other vanilla but at least on this part, the vanilla xpac the scripting is much much better than other legion ones with probably less bugs than theirs.

**Comment by taktrix** [comment]
That's because the legion servers you're talking about all worked on their legion content and none of them worked on the vanilla content, so of course your vanilla content will be better scripted, they didn't do any work on it. But if you're going to be comparing scripting content then you should really compare your vanilla scripted content to their legion scripted content since that's the content they worked on.

**Comment by Serithul** [comment]
Their legion content is at best mediocre since half the stuff aren't working properly and instead of fixing them they just added a workaround for players to not be obstructed. Freakz for example has a legion dungeon boss that more or less is a dummy, making players able to clear m+ content without being a challenge for them. I prefer being "stuck" in a great vanilla content legion server than playing on a semi working legion only content, since there are a lot more to do in WoW than just the end game content.

**Comment by taktrix** [comment]
That might be true but here's the problem, you're not making a vanilla server, you're making a legion server. And while you might have better scripted vanilla content it really means nothing to people who came to this server to play LEGION.

**Comment by Serithul** [comment]
If people come here, on a BETA PTE server, to play legion, then it's their problem for wanting that. It is clearly stated everywhere that this server is in a Beta phase following a PTE type of progression/testing. Being ignorant of that is not the servers problem.

Having a good foundation, can lead to having a sturdy and well structured top. And this can be seen on many servers who took their time to script old xpacs too, like tauri, who follows another style of PTE progression.

**Comment by taktrix** [comment]
I agree with you about having a good foundation, I think it's one of the biggest drawbacks to most servers, but it isn't ignorance when you advertise this server as a legion server for people to expect legion content.

It's like advertising a home based on a built deck, I'm sure the deck is new and shiny and perfect, but if the rest of the house is a bunch of sticks it's not really a home is it?

**Comment by Serithul** [comment]
It is ignorance, because it is advertised as a Legion PTE Beta server. Clearly stated in PTE that the server will Progress Through Expansions, hence PTE. You can check all of the posts on reddit and the homepage of the server. It's almost written everywhere xD

**Comment by taktrix** [comment]
Ok lets say you do exactly as you want right? Which is the ideal scenario. How long roughly do you estimate it would take to get to legion content construction and work? Because at the end of the day that's what it comes down to. It comes down to 1 simple question. "When can I play a good working version of this game on this server?"

**Comment by Serithul** [comment]
It is advertised as it is. I don't what you read and where but on all official reddit post the PTE is clearly stated and the vanilla cap is in the server description. If people don't read the whole article and just focus on 3 words they saw quickly, its their fault if they expect to see something else.

**Comment by taktrix** [comment]
Yea we're beyond that, I'm asking how long until you estimate you guys get to doing legion content. Because by your own description you have to go through every single xpac up to legion. And that's A LOT of xpacs. By my count that's 6, you have to do and cover 6 xpacs until you START legion. And then there's a few years worth of work to really properly do legion.

**Comment by Serithul** [comment]
There is no way a timeline answer can be given because there is no way to tell what other obstacles the devs will meet in their way to fix the server. A good legion scripted server will take about a 1-1.5 year to be made if not many obstacles are met, in theory.

**Comment by taktrix** [comment]
So best case scenario like 3 months an xpac? Because that's roughly how long you would have to do each xpac before you got to the 1.5 year mark. And that's the start of legion, not even like scripted legion, because if we're talking about scripting it too then that's between 2 and 2.5 months an xpac. That is some serious crunch.

**Comment by Serithul** [comment]
3 months per xpacs if some core issues still persist. If the core issues affecting stuff xpac wide are fixed, the time will be shorter for each xpac after vanilla.

**Comment by taktrix** [comment]
Well I hope you succeed, I really do. I think if you can do that, you can make this the best server ever.

**Comment by Serithul** [comment]
We will succeed because we, the community, are really eager to help the devs out and the devs are doing their hardest whilst approaching us to test stuff for them. My personal estimation, without having any inside information, is that this server will release a bit sooner than Tauris', since they are working on their wotlk too.

**Comment by taktrix** [comment]
Well I will do what I can to help, I'll just keep on bug reporting. Hopefully it speeds things along.

**Comment by Serithul** [comment]
It will, every single bug report, if not duplicate, helps a lot.

**Comment by taktrix** [comment]
Anything I can do, I love beta testing, I did it for blizzard and those ungrateful fucks ruined such a beautiful game with their stupidity, it will be nice to see a server that doesn't ruin it.
