### ISSUE TITLE
[Core] - Monk Class Overview

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#1296]
**Links:**
https://www.wowhead.com/spell=205523/blackout-strike
https://www.wowhead.com/spell=100784/blackout-kick
https://www.wowhead.com/spell=121253/keg-smash
https://www.wowhead.com/spell=100780/tiger-palm
https://www.wowhead.com/spell=115098/chi-wave
https://www.wowhead.com/spell=198898/song-of-chi-ji
https://www.wowhead.com/spell=137639/storm-earth-and-fire
https://www.wowhead.com/spell=157411/windwalking
https://www.wowhead.com/spell=113656/fists-of-fury
https://www.wowhead.com/spell=101546/spinning-crane-kick

**What is happening:**

**Overall**
Monk spells/attacks, in all specs, do approximately 70% of the damage that they should be doing.

_**[Brewmaster]**_
**Blackout Strike,** **Blackout Kick**, and **Keg Smash** damage is low.
**Tiger Palm** damage is low, and does not reduce the cooldown of the Monk's Brew spells (**Celestial**, **Ironskin**, **Purifying**, and **Fortifying Brews**).

_**[Mistweaver]**_
All heals need a slight increase. Mistweaver Monks are currently doing 96% of what their total healing is supposed to be doing.
**Chi Wave** healing is not consistent with each bounce.
**Song of Chi-Ji** does not disorient the targets within range.
**Ring of Peace** does not eject enemies within range.

_**[Windwalker]**_
**Storm, Earth, and Fire** Does not reduce damage done and does not curate images of the Monk to deal damage.
**Wind Walking** does not increase the Monk's, or their party member's, movement speed.
**Fists of Fury** does 60% of its normal damage.

**What should happen:**
_**[Brewmaster]**_
**Blackout Strike,** **Blackout Kick**, **Tiger Palm**, and **Keg Smash** damage needs a slight increase ~10-15%.
 **Tiger Palm** should reduce the cooldown of the Monk's Brew spells (**Celestial**, **Ironskin**, **Purifying**, and **Fortifying Brews**).

_**[Mistweaver]**_
Increase healing of spells.
**Chi Wave** healing should be consistent with each bounce.
**Song of Chi-Ji** should disorient the targets within range.
**Ring of Peace** should eject enemies within range.

_**[Windwalker]**_
**Storm, Earth, and Fire** should reduce damage done and curate images of the Monk to deal damage.
**Wind Walking** should increase the Monk's, or their party member's, movement speed.
**Fists of Fury** should have increased damage.

**Comment by sweetloo32** [comment]
Every spell that deals damage that Monk has when doing the math and taking percentage of the damage dealt compared to the tool tip the spells are doing 72%of the tooltips stated damage.
e.g. Blackout Kick, Rising Sun Kick, Tiger Palm, etc. 
This is after further testing of damage done to mobs and did it based off of health removed after hitting the mob to determine actual damage since damage logs are a little buggy.
Fists of fury isn't lower as I thought but instead it is the same 72%
Chi Wave seems to heal enemy mobs(have not tested if heals enemy players)
There's also a bug involving spinning crane kick, but it's probably easier to explain over discord. Nathan can direct you to me.

**Comment by NightwindOI** [comment]
count the mob armor or not? Since armor reduces a lot of male dmg.
