### ISSUE TITLE
Flying mount in water

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1558]
Links:
https://www.youtube.com/watch?v=qMu3xOBe7Fw&feature=youtu.be&t=48

What is happening:
If you ride your flying mount in the water, you start to drowning, over the water. And you can't jump out to start to fly, because you are still drowing even over the water. (the druids involved here too, the bug there has more visual, there is a 0,2-0,3 sec stag form between the aquatic and flight form, which is pretty lame, there is no stag form in the water or in the air)

Note: (https://github.com/GuabinaCore/WoWKoi/issues/1545) this is the same, just the video is from Mists of Pandaria (5.4) so you can't close with bullshit reason like not implemented in legion.

What should happen:
If we are over the water, we can't drowning and die, and we need to fly out of the water with a simple jump. Also eliminate the stag form between aquatic/flight form for druids if we jump out of the water.

**Comment by Thordekk** [comment]
Not bug present, fly mounts not fly in water played in blizzard legion and its same system

**Comment by Velthur-bot-3000** [comment]
This issue is not fixed.  
When you are in water you are allowed to mount, but then you cant fly.  

You are allowed to enter the water when mounted or travel form as well, currently cannot do that either.  

As well as, when you mount touching the water, you cant fly it does not allow you to fly after mounting either inside the water, or touching it, you have to unmount and re mount to fly.

**Comment by Thordekk** [comment]
that is not a bug try where u want system in legion work like that
