### ISSUE TITLE
Enter The Ilidari: Ashtongue - DH starting zone quest

### ISSUE THREAD

**Issue by Filqkus** [GuabinaCore/WoWKoi#1632]
**Links:**
https://www.wowhead.com/quest=40378/enter-the-illidari-ashtongue
**What is happening:**
Upon clicking the Legion Gateway Activator, nothing happens, the npc runs away and the quest is not flagged as completed

**What should happen
Upon clicking the Legion Gateway Activator the Ashtongue forces should arrive and the quest should be flagged as completed.

**Comment by Cefiro-Caecias** [comment]
Dear Filqkus, good morning. Yes, I already did almost all the repairs for Mardum + Vault of the Wardens, just uploaded them. However, there are some pending details so that it is 100% ready, and that my partner Arthas will have to do:

1.- Adjustments in the battle against Beliash.
2.- Adjustments in the battle against Tyranna.
3.- Settings in the A New Direction quest.

That is why I did not notify the Community that they could already test the DHs. Impatient :P
