### ISSUE TITLE
One of the Ashenvale quests cannot be completed.

### ISSUE THREAD

**Issue by usernamenotavaible02** [GuabinaCore/WoWKoi#1640]
**Links:**
https://www.wowhead.com/quest=13888/vortex# 
from WoWHead or our Armory

**What is happening:**
When doing the Vortex quest in Ashenvale, after finishing it the npc doesnt appear so you can complete the goal, but cannot turn in the quest.

**What should happen:**
The npc that you're supposed to turn in the quest to should appear after you land on the ground.

**Comment by Cefiro-Caecias** [comment]
I just tried the Horde and Alliance quest, and it doesn't give me any bugs. In fact, the system is programmed so that you can see NPC Ali or NPC Horde when you complete the quests "Go With The Flow" or "Thunder Peak", respectively. Check that you are not transformed into any beast, clear Cache and re-enter the game to test it.

**Comment by Cefiro-Caecias** [comment]
I just understood the problem you had. The Horde NPC becomes visible when you complete the quest "Thunder Peak", programmed by spell_area. However, the quest "Vortex" is activated by completing the quests "Hot Lava" and "Put Out The Fire", but not having completed the quest that I mention, you did not "see" the NPC to deliver it.

When I overhauled the breadcrumb system to make the trigger requirements less tyrannical, I forgot to release this requirement in spell_area. I've already corrected it for Alliance and Horde, and by tomorrow it will work as normal.

Fixed. Available in the next update.
