### ISSUE TITLE
The Fallen Lion - Legion - Quest (Broken Isles)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1786]
**Links:**
https://www.wowhead.com/quest=40517/the-fallen-lion
from WoWHead or our Armory

**What is happening:**

1) You dont get the letter
2) After the NPC give some talk to anduin about their suport and that he isnt alone. nothing else happens. the script stop and anduin doesnt give the final speech.

**What should happen:**

https://www.wowhead.com/quest=40517/the-fallen-lion#videos:id=98799

**Comment by NightwindOI** [comment]
i cant turn the pre-part too
https://www.wowhead.com/quest=42740/the-battle-for-broken-shore

**Comment by Nephilimkoi** [comment]
![image](https://user-images.githubusercontent.com/73371905/100136538-8d2a5800-2e61-11eb-8d18-160052336e9f.png)

**Comment by Cefiro-Caecias** [comment]
Hello, children.

1.- The quests "The Battle for Broken Shore" were temporarily put in autocomplete mode, until the whole adventure was repaired.

2.- Repaired the quest "The Fallen Lion". Then I will see to add the item of the letter, since currently it does not exist in the DB. Available in the next update.
