### ISSUE TITLE
to the dreamway 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#1980]
after you do the ritual and open the dreamway there is a mini quest called ( to the dreamgrove cleanse the corruption ) 
mini mobs are op when they hit you and the main mob that you should kill does not respawn

**Comment by Cefiro-Caecias** [comment]
I need more precise information on which mobs you consider to be too powerful, either because of their physical attacks, because of their spells, or because of how often they throw their spells. For this part of the scenario, there are 4 types of mobs:

- Blightthorn Growth: https://www.wowhead.com/npc=103240
- Echo of Nightmare: https://www.wowhead.com/npc=101091
- Bloodcrazed Screecher: https://www.wowhead.com/npc=103742
- Nightmare Blight: https://www.wowhead.com/npc=103246

As for respawn, these creatures are for single use only; They will respawn after 2 hours. But if you leave the area and re-enter, they will have automatically respawned, as long as you have not completed or turned in the quest.

**Comment by NightwindOI** [comment]
Echo of Nightmare need mele dmg nerf x3 timer (now they hit for 35k...suppose to hit for like 10k)
Anything else work fine...mobs are fine and boss is there.

**Comment by Cefiro-Caecias** [comment]
Echo of Nightmare, fixed. Available in the next update.
