### ISSUE TITLE
Shadow Artifact Quest line bug

### ISSUE THREAD

**Issue by reqlay** [GuabinaCore/WoWKoi#2045]
**Links:**
https://www.wowhead.com/quest=40710/blade-in-twilight

**What is happening:**
If you die during the "Stage 8 Death to the Deacon" mission of the scenario, you are unable to finish the quest since you can't go back to the Tomb of Tyr since there is an invisible wall blocking your way.

**What should happen:**
You should be able to walk through open door.

**Other things:**
The tentacle mobs don't work correctly. They should die by dispelling them.

**Comment by reqlay** [comment]
You can also drop down to the ravine just before the last boss and be stuck there.

**Comment by reqlay** [comment]
To clarify, only mass dispel works on tentacles.

**Comment by reqlay** [comment]
Okay the invisible wall must've been a random bug since it didn't happen on the 2nd attempt of the quest. Altough the last boss does seem to hit a tad bit too hard where you just need to spam heal yourself just to die when you run oom.

**Comment by Cefiro-Caecias** [comment]
Regarding the damage they take in those quests, we have been on it, and we have come to the conclusion that it is due to the low level of equipment that they receive in the Promo, since those mobs are designed as if they carry the best equipment of Draenor. All that remains is for Guabina to authorize the improvement of items in the Promo.
