### ISSUE TITLE
Quest - Runas the Shamed

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2205]
**Links:**
https://www.wowhead.com/quest=37957/runas-the-shamed

**What is happening:**
The mob simply dies, making it unable to follow the player to complete the quest.

**What should happen:**
After killing Runas, he should become friendly and follow the player until reaching Senegos, completing the quest.

![WoWScrnShot_040221_151146](https://user-images.githubusercontent.com/64436148/113418596-17fa0100-93c6-11eb-9318-cd31330259d0.jpg)

**Comment by Cefiro-Caecias** [comment]
There is no bug present on my Test Server, and I tested that mob twice in a row. Even so, what you send is very strange, since that mob has a security device to never die; Not even GMs can kill him, but in your photo he appears dead, and besides, his invocation script doesn't seem to have worked either. I'll ask for a system check.

**Comment by Cefiro-Caecias** [comment]
Fixed, now available.
