### ISSUE TITLE
[Legion][Professions][Cooking] Nomi Work Orders

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2635]
**Links:**
https://www.wowhead.com/quest=40991/opening-the-test-kitchen
https://www.wowhead.com/npc=101846/nomi

**What is happening:**
Nomi gives no options for Work Orders to research recipes.

**What should happen:**
After handing in 'Opening the test kitchen' You are now able to start Work Orders for any type of Legion meat or fish you possess. Each Work Order lasts 4 hours. Creating a Work Order with a specific ingredients has a chance to teach you a recipe that uses that ingredient. In 7.1, Nomi will refund you one piece of meat when the order is complete.

There is a high chance you will get Badly Burnt Food back from your Work Order, so don't dump all of your cooking reagents into Work Orders. There is also a chance you can get duplicate recipes, so it seems better to queue up a variety of Work Orders with different ingredients, instead of queue up Work Orders for one type of reagent.

All Rank 2 and Rank 3 recipes come from Work Orders. Several Rank 1 recipes are from Work Orders, but most are from quests or rare spawns.
![image](https://user-images.githubusercontent.com/85613053/126092640-52bc4734-b261-4df9-a6cb-f8f0ee88aab4.png)

**Comment by Cefiro-Caecias** [comment]
Repaired, although only in part. The system has many technical problems. For the moment, this is what can be done:

1) Only one Work Order can be investigated every 4 hours.
2) If the Server is rebooted for any reason, the Work Order is lost, but the 4 hour timer remains, and another Work Order cannot be started until the deadline expires.
3) Work Orders do not consume items.

I know, this workaround sucks. However, in order to make this work blizzlike, you have to design a complete new system, unique to this task. So patience.

Temporal fixes available in the next update.
