### ISSUE TITLE
[Quests] - Huln's War (pretty much all of them)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#2852]
**Links:**

https://www.wowhead.com/spell=193237/wild-carve
https://www.wowhead.com/spell=193016/gore-charge

**What is happening:**

When you press forward (Z or W or whatever your keybind is) and use the charge. Your character doesn't charge. Works well if you don't press forward.

Gore Charge doesn't deal damage

Wild carve doesn't deal enough damage. (see https://www.wowhead.com/quest=39983/hulns-war-the-arrival#videos:id=102445 at 0:35)

You should be able to spam Wild Carve.

**What should happen:**

Should charge normally even if forward is pressed and should deal damage.

**Comment by gigaslurp** [comment]
I managed to kill all the mobs (25 legion) for the first part of the quest by grappling hooking around to get closer to mobs so I could carve and kill them.
Afterwards exited the tauran vehicle and walk around as your player character.
As the player character, you can complete [Huln's War - Malorne's Favored](https://www.wowhead.com/quest=40112/hulns-war-malornes-favored), [Huln's War - Stormrage](https://www.wowhead.com/quest=39988/hulns-war-stormrage) and you're actually able to also complete [Huln's War - Reinforcements](https://www.wowhead.com/quest=39990/hulns-war-reinforcements) since the wrathguards don't actually attack you. It takes a long time since they have so much health, but its _doable_. (as a subtlety rogue, i just spammed shuriken storm, used nightblade once, and spammed eviscerates since they all stand in 1 place) You're then able to complete [Blessing of Cenarius](https://www.wowhead.com/quest=39991/blessing-of-cenarius) since its just another npc meetup quest. After that, [Huln's War - The Nathrezim](https://www.wowhead.com/quest=39992/hulns-war-the-nathrezim) is seemingly incompletable since Tichondrius actually targets the player and has a lot of health. The player just dies.

**Comment by nazgrim94** [comment]
Nuevo inconveniente en la mision.  Huln's War - The Nathrezim 
EL NPC o Add Tichondrius se vuelve imposible de matar porque sale evadir todo el tiempo cuando se ataca y aparece con menos del 100% de la vida.... Pero al final me puedieron ayudar para avanzar gracias

**Comment by Cefiro-Caecias** [comment]
Fixed.
