### ISSUE TITLE
guardian druid artifact bugg

### ISSUE THREAD

**Issue by ruriro** [GuabinaCore/WoWKoi#2990]
**Links:** 

from WoWHead or our Armory

**What is happening:** getting stuck in combat after second wave of adds. 4/8 on the story line in ursoc's lair.

**What should happen:**

**Comment by ruriro** [comment]
it seems iff you kill the adds slower you dont bugg out the waves. but still not the correct way to do it

**Comment by djawl** [comment]
https://imgur.com/qWZ5xv8
https://imgur.com/MTzq1Pz
https://www.wowhead.com/npc=101388/rothoof-shadowstalker

Seems there's some bugged interraction with the "[Rothoof Shadowstalker](https://www.wowhead.com/npc=101388/rothoof-shadowstalker)" appearing. It's completely invisible and can't be attacked. But since it's considered alive the scenario waves can't continue.

This bug seems to consistently happen now. Seemingly impossible to finish the quest rendering one classes artifact weapon unobtainable. Which obviously is a **HUGE** problem.

**Comment by ShikoSCS** [comment]
Fixed
