### ISSUE TITLE
[Tyce] - Blood Dk Artifact questline

### ISSUE THREAD

**Issue by ExonHUN** [GuabinaCore/WoWKoi#3004]
**What is happening:**
This is ok scripted, but it doesnt spawn Maw of the Damned when defeating the elite that holds it.
But the Death Gate spawns, and I cant finish the quest.

**What should happen:**
Spawn Maw of the Damned so we can get the weapon.
https://www.wowhead.com/quest=40740/the-dead-and-the-damned

**Comment by Sariet** [comment]
**FIXED AFTER RESET 11/13/21**

The script is kinda bad because all the mobs are spawned and if you accidently kill a mob that wasn't supposed to be there yet then Baron Sliver bugs and goes afk.

Edit: Even killing them in the order you should need to, the scenario chain bugs and is not able to be completed.
Edit2: Abandoning the quest, Exiting the game, & deleting cache made the scenario work but the entire time from the beginning its like theres an extra mob there but acts as the trigger for the scenario.
![image](https://user-images.githubusercontent.com/88337786/141655025-672c288b-a372-493b-9668-77c83687115e.png)
Whats supposed to happen: https://youtu.be/x9GL_P9lQ7g
0:53 - 1:15
