### ISSUE TITLE
[Demon Hunter] (Class Hall Scouting Map) Direct Our Wrath Quest ID 41069

### ISSUE THREAD

**Issue by gigaslurp** [GuabinaCore/WoWKoi#3022]
**Links:**

[https://www.wowhead.com/quest=41069/direct-our-wrath](https://www.wowhead.com/quest=41069/direct-our-wrath)

**What is happening:**
I was able to choose a starting location (I chose azcuna) on the scouting map before taking the quest from Kayn Sunfury. When I then got the actual quest, I tried picking a starting location, but it just doesn't work. I try to click accept, but all it does is visually make the UI element disappear without completing the original quest objective or starting the new one. If I exit and re-open the scouting map, the starting location that I attempted to pick was still there. I tried abandoning both quests then re-accepting Kayn's quest, but it's still broken.
[https://www.youtube.com/watch?v=DzjonbF9hAQ](https://www.youtube.com/watch?v=DzjonbF9hAQ)

**What should happen:**
The player shouldn't have access to the scouting map before receiving the quest (Direct Our Wrath) at all.

**Comment by IcePunchG** [comment]
[https://cdn.discordapp.com/attachments/637812015494070286/909149416257122304/Class_Hall_Broken.mp4](https://cdn.discordapp.com/attachments/637812015494070286/909149416257122304/Class_Hall_Broken.mp4)

**Comment by Cefiro-Caecias** [comment]
Fixed. Added extra security measures so that the Scouting Map is not activated prematurely. Available in the next update.

Instructions:

You will have to leave the quest for a security script to be applied to reset the Scouting Map quests. If you have already left the "Direct Our Wrath" quest, you take it and leave it again. Then you take it again, and you go to the Scouting Map, which should already work correctly; if not, try a second time.
