### ISSUE TITLE
artifact knowledge(extremely important)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#3141]
**Links:**

https://www.wowhead.com/currency=1171/artifact-knowledge#comments:id=2349316

**What is happening:**
so, right now, upon getting an artifact, a player gets x4 artifact knowledge(for unknown reasons). to continue upgrading an artifact, player is forced to increase level of artifact knowledge in the way described in the link atop.  but theres no quest to start researching for next levels of artifact knowledge, npc ( the <archivist > npc, like this in rogue class hall 
![image](https://user-images.githubusercontent.com/77908571/141753237-a16e21bf-40d7-4ee3-a27c-bb1cf7dc8d7f.png) is just standing, offering nothing.

**What should happen:**
appropriate quest ( Hitting the Books) should be available to pick from the <archivist > npc, which stands in each class's class hall. after completing it, player should be able to order a research(2 researches at the same time btw) for 500 order resources to get another level of artifact knowledge. 
P.S. this is the most important thing, since artifacts impact player's powers the most and has to be fixed asap. right now its impossible to increase lvl of artifact knowledge. that leads to player's inability to upgrade artifact and increase character's powers.

**Comment by Ghlimk** [comment]
In Patch 7.3 Artifact researches have permanently become a weekly automatic process and players can not research manually anymore. Due to this change, the research scrolls have become grey trash items, and all of the information for previous patches are now obsolete.

You'll get a new level of Artifact Knowledge every week.

**Comment by menelys** [comment]
and what? server is fresh, 7.0.  it was said so. and try to think of why it was removed in 7.3 and why it cant be like that in 7.0 , just try to think once, helps a lot

**Comment by Ghlimk** [comment]
Maybe you should try to think, because the server is 7.3.5 not 7.0. and all the systems are the ones in 7.3.5, it doesnt matter if they choose to give us content from 7.0 onwards. Because that content exists in 7.3.5, but all the previous systems that got changed before 7.3.5 doesnt exist in the game anymore.
