### ISSUE TITLE
Quest in Suramar bugged 

### ISSUE THREAD

**Issue by conyoshi** [GuabinaCore/WoWKoi#3538]
Hi, the quest "Search and Rescue!" (41140) is bugged: The key that must be obtained from a wall to free Brambley is bugged and cannot be clicked. Pls help
Thanks :)

**Comment by Noahkrr** [comment]
Try to kill the weird at the end of the tunnel, go back to where the key is and take it. It worked like this for me

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by conyoshi** [comment]
thanksss

**Comment by conyoshi** [comment]
Nvm the key doesnt work yet :(

**Comment by Cefiro-Caecias** [comment]
Honey: "Available in the next update", it means that the fix will be applied the day after this publication, in the morning, Argentina time (which is where I live, since I take care of the daily updates). While I'm writing this, I'm already preparing to do it, so in 10 minutes everything will be up to date and operational ;)
