### ISSUE TITLE
Legion Raid - Emerald Nightmare (EN) - bugs we've found

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3553]
---
1. 
 - [ ] [Nythendra](https://www.wowhead.com/npc=102672/nythendra) is rotating around after her target during [Heart of the Swarm](https://www.wowhead.com/spell=203552/heart-of-the-swarm). She should be immobile during that time.
 - [ ] [Rot](https://www.wowhead.com/spell=203096) ability targets a tank, that is not currently tanking the boss. It should not target any tank, because tanks already have to handle Volatile Rot.
As a proof, according to wowhead guide, this are the only tasks tanks should take care of: (no Rot included)
![image](https://user-images.githubusercontent.com/63166930/150687381-4df0bc5e-4b61-458a-9670-dd5aa358485d.png)

---
2. 
 - [ ] [Deathroot Ancient](https://www.wowhead.com/npc=111528/deathroot-ancient)s sometimes don't have "death" animation, which leave them standing.
    
---
3. 
 - [ ] [Dire Shaman](https://www.wowhead.com/npc=112153/dire-shaman)s cast [Corrupted Totem](https://www.wowhead.com/spell=223918/corrupted-totem). The totem is not target-able. The totem should be target-able and kill-able.
  
---
4. 
 - [ ] Ursoc's [Focused Gaze](https://www.wowhead.com/spell=198006/focused-gaze) sometimes targets off-tank. It should never target a tank/off-tank. Focused Gaze also seems like it has too large radius. It hits people that are behind the boss.
    Proof and source: https://www.wowhead.com/ursoc-strategy-guide#focused-gaze-barreling-impact
   
![image](https://user-images.githubusercontent.com/63166930/148592253-9cd6c383-bb49-4729-99a5-0bdd01879ec7.png)

---
5. 
 - [ ] [Il'gynoth](https://www.wowhead.com/ilgynoth-strategy-guide) requires an over-haul of entire fight. It feels nonsense to point every single bug. I can provide more detail if you get to fixing the fight.
    
---
5. 
 - [ ] Item level scaling seems to be a little bit off. According to reference information online, EN has base 850ilvl with a chance to upgrade the item. During our run, we dropped items with 865ilvl. I can't confirm if that 100% an issue, so it will need additional confirmation.
    
---

**Comment by Travven** [comment]
" Ursoc's Focused Gaze sometimes targets off-tank. It should never target a tank/off-tank. Focused Gaze also seems like it has too large radius. It hits people that are behind the boss.
Proof and source: https://www.wowhead.com/ursoc-strategy-guide#focused-gaze-barreling-impact"
This mean it will never target the tank, the one who is tanking.

"Rot ability targets a tank, that is not currently tanking the boss. It should not target any tank, because tanks already have to handle Volatile Rot.
As a proof, according to wowhead guide, this are the only tasks tanks should take care of: (no Rot included)"
This hability target any melee that is not tanking the boss just that.
