### ISSUE TITLE
[Quest] In the Blink of an Eye

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3906]
**Links:**

https://www.wowhead.com/quest=44184/in-the-blink-of-an-eye
https://www.wowhead.com/quest=44663/in-the-blink-of-an-eye

**What is happening:**
Quest has no problem, but the zone you get ported (old Dalaran) in is bugged. You cant target the NPCs, they do too much damage and its chance.
Some guards are missing too.

**What should happen:**
https://youtu.be/xU0a7G4ioSU?t=56

**Comment by Cefiro-Caecias** [comment]
1.- Reduced area damage from enemies.

2.- At the moment, the enemies will not attack the players, nor can they be attacked by them, due to defects in the Vmaps of the area, which make the enemies fall into the void or go through the game textures if they move too much , in addition to the fact that due to the same defects they must be permanently in flight mode. Due to these considerations, the battle in the city will be permanent and only for cosmetic purposes, without intervention of the players, who will only have to dodge the area damage (reduced now), to reach Khadgar.

Available in the next update.
