### ISSUE TITLE
Silverpine Forest

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3919]
Silverpine Forest:

#1 Steel Thunder - https://www.wowhead.com/quest=27069/steel-thunder
	
	- Admiral Hatchet doesnt have an option to spawn lost Orc Sea Pup
	

-------------------------------------------------------------------------------
#2 Rise, Forsaken - https://www.wowhead.com/quest=27097/rise-forsaken

	- If Agatha dies, she will duplicate herself.

-------------------------------------------------------------------------------
#3 No Escape - https://www.wowhead.com/quest=27099/no-escape

	- Enemy monsters are interrupting sequence of the "Run" script. The valkyrie is attacking the monsters instead of forced pathing.

-------------------------------------------------------------------------------
#4 Lordaeron - https://www.wowhead.com/quest=27098/lordaeron

	- If you skip the cut scene and dismount, it will still teleport the player to the Sepulcher at the end of the script.

-------------------------------------------------------------------------------
#5 Hair of the Dog - https://www.wowhead.com/quest=27226/hair-of-the-dog

	- If the player is fighting Hillsbrad Worgen (45255), nearby corpse of Orc Sea Dog (4519) will trigger and disappear.

	https://www.wowhead.com/npc=45255/hillsbrad-worgen
	https://www.wowhead.com/npc=45196/orc-sea-dog-roused

-------------------------------------------------------------------------------
#6 The Waters Run Red... - https://www.wowhead.com/quest=27232/the-waters-run-red

	- There seems to be 7 sec invisible cooldown on Rocket Blast - https://www.wowhead.com/spell=78294/rocket-blast
	- Cosmetic: Worgens are walking across the water instead of swimming

-------------------------------------------------------------------------------
#7 Vengeance for Our Soldiers - https://www.wowhead.com/quest=27360/vengeance-for-our-soldiers#comments

	
	- 7th Legion Submariner are missing around the questing area - https://www.wowhead.com/npc=45403/7th-legion-submariner

**Comment by Cefiro-Caecias** [comment]
1.- Fixed. The Admiral Hatchet will allow you to recruit a new Orc Sea Pup, if the one you owned disappears during the quest.

2.- Fixed. Agatha will never die.

3.- Fixed. Added security measures.

4.- Fixed. Added security measures.

5.- Fixed. Added security measures.

6.- Spell Rocket Blast (84575), Core area. Worgens: in effect, we calibrated for the Worgen to walk on water instead of walking, since otherwise it would cause unsolvable glitches due to texture issues.

7.- In progress, I haven't gotten to that quest yet.
