### ISSUE TITLE
[Core] - Mining

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#4]
Mining gray ores gives you skill-points.

**Comment by Cefiro-Caecias** [comment]
Para los devs de Core: al parecer no es un problema de DB ni de los objects ni del Config. Según parece, te deja seguir subiendo puntos de profesiones ilimitadamente sólo minando, desollando o recogiendo hierbas con lo más básico de todo (menas de cobre, etc.).

**Comment by Arkanheal** [comment]
English translations : 

> For Core devs: Apparently not a DB or an Object or a Config issue. Apparently, it lets you continue raising profession points unlimitedly only mining, skinning or collecting herbs with the most basic of all (copper ores, etc.).

**Comment by Velthur-bot-3000** [comment]
Still currently happening.  

https://www.worldofmoudi.com/mining

This is an old WoD mining guide, as you can see. after skill level 50, mining copper is useless, either gives you minimal exp/or wont give a skill up mining it.  

Each level shown for each low level ore is around when it stops giving skill levels and just is grey, but you get extra ore drops form those because of your skill being so high.  that's the benefit of the new system, higher drop rates on the ore that doesn't give you skill levels.  Once past level 50, copper should no longer skill up, but should drop extra ore.  

Same for other low level ores, when they are grey, they no longer give skill levels, but extra ore. confirmed it happening with tin as well.
![WoWScrnShot_072520_151233](https://user-images.githubusercontent.com/43558040/88464498-47e12400-ce89-11ea-826a-b8a9ecb3f427.jpg)
