### ISSUE TITLE
Hero's Call related, can't get quests

### ISSUE THREAD

**Issue by WorgenxX** [GuabinaCore/WoWKoi#714]
**Links:**

from WoWHead or our Armory

**What is happening:**
Some areas just let you take their quests if you have completed the Hero's Call quest before 
Didn't tried every zone , but Ashenvale 100% sure, and pretty sure Darkshore too, probably there are more zones like this.
Someone had the same issue in Westfall

**What should happen:**
We should be able to take quests from areas that are compatible with our lvl without needing to complete that area's Hero's Call first

**Comment by Cefiro-Caecias** [comment]
There are currently two ways to unlock quests from a map:

1.- Take the quest from the Board: Hero's Call / Warchief's Command.
2.- Complete the penultimate quest on the previous map, which gives you as a reward the connection quest with the following map.

The only quests that are unlocked only with a level requirement are those that send you to Dungeons / Raids.

Server Policy. We hope you suffer and enjoy it :D

**Comment by Maczuga** [comment]
@Sefrenia-Caecias Sorry, but this is wrong. Hero's call and warchiefs board quests are breadcrumb quest that should optionally point player to location that's currently available for him. Player should be able to zone without having to go to capital city or using adventurers journal. This is really counterintuitive and forces a bad experience to players that already completed those quests on retail. Both examples you provided are breadcrumb quests - you are not supposed to complete previous zones in order to go further.

A lot of quests are locked like that right now and players have no idea that they MUST do optional breadcrumb quests.

In TrinityCore there is a special column for that 'BreadcrumbForQuestId': https://trinitycore.atlassian.net/wiki/spaces/tc/pages/34897928/quest_template_addon#quest_template_addon-BreadcrumbForQuestId

Please consider implementing that.
