### ISSUE TITLE
[Core] - Spell - Talent level 30 Inspiring Presence (Protection Warrior)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#801]
**Links:**   [wowdb](https://wow.gamepedia.com/Inspiring_Presence)

from WoWHead or our Armory

**What is happening:**
Protection warriors gets the benefit of their own Inspiring presence buff

**What should happen:**

Apparently up from [patch 7.1.0](https://wow.gamepedia.com/Patch_7.1.0#Warrior) and different sources across the internet ([this](https://www.reddit.com/r/wow/comments/4tohbn/warrior_inspiring_presence_and_soloing/) and [this](https://blizzardwatch.com/2016/09/14/patch-7-1-ptr-patch-notes/) amongst others). Inspiring Presence shouldn't heal the warrior but only his raid or party members.
Which means that if there is 2 protections warriors with this talent in the group they have to benefit from one another and the buff does not stack for other party members.

**Comment by PilavKOI** [comment]
if you watch method / swifty / asmongold videos you should see that the aura affects & heals the protection warrior ive been playing retail & all private servers of legion that's pretty False 
it surely says it should affect your party & raid members & i blame blizzard for false writing
as a pvp player i always took it instead of [Impending Victory] bcz of the healing it provides when you have a lot of damage specially when you are 970+ ilvl. 
You are a party/raid member ^
if you don't believe what i am saying with experience of warrior (my main class) check every single private server 7.3.5 and videos of the patch yourself.
https://www.youtube.com/watch?v=W3wUtn2eA8E
https://www.youtube.com/watch?v=QcYHCZVvOxM
what you read is different of what you play. False report bro.
https://www.youtube.com/watch?v=ayq9aJk3HBk
asmongold is not that dumb to take inspiring presence on the hardest challenge mode in legion if you watch the fight careful you can see the healing done as he damages. i know he has the bracers legendary but it only heals for 1%. of each 10 rage you only.
the nerf to inspiring presence was bcz it was too broken giving the buff to non-party/raid members in open world you can see the difference here https://www.youtube.com/watch?v=rmtFLX_cVqQ
https://wow.gamepedia.com/Inspiring_Presence that was why..

**Comment by PilavKOI** [comment]
This is complete proof & research that the current report is False !

**Comment by Arkanheal** [comment]
Bro, Asmon told himself that he was a complete idiot for specing into Inspiring Presence ([see](https://www.youtube.com/watch?v=ayq9aJk3HBk&t=3m10s))

**Comment by Maczuga** [comment]
Reposting from Discord:

http://web.archive.org/web/20180223054448/http://www.wowhead.com/spell=205484/inspiring-presence#comments

"It does not affect the Warrior. However, if another Prot Warrior in your group is spec'd into this, you receive the buff from them."

**Comment by Arkanheal** [comment]
To further add prrofs, [here](https://www.warcraftlogs.com/reports/t92vDaBJ7nYmRrHC#fight=4&type=healing&source=10&ability=222944) a 100% parse from a protection warrior in Antorus. As you can see on the meters the warrior didn't get heal by his own buff.

**Comment by PilavKOI** [comment]
i did test on every single legion private server specially the top & bad ones had the same results.
The talent is scripted well. does provide the warrior healing. You cant prove points of view from links
You have to test it yourself i have played with it in retail from the start of legion until the end. i dont want to force it to be working that way but that's how it should be working.
learn your class before judging it plz. as i want the best for this class to be running smooth / blizz like for everything. 
https://cdn.discordapp.com/attachments/697056287501975562/701017007939780638/unknown.png
& also that i have asked most of my retail friends & they said that it healed the warrior also. imagine having an hour providing your party 3% healing without benefiting from it yourself.. if you are not a party/raid member are you a wall maybe ? xD ???

**Comment by PilavKOI** [comment]
also Arkhan there is an option to choose target healed by source which is here buddy no problem ^^<3 i love u
https://www.warcraftlogs.com/reports/t92vDaBJ7nYmRrHC#fight=4&type=healing&source=10&by=source&options=6&ability=222944
https://imgur.com/Pt7FryM
https://imgur.com/a7gGyvn
https://imgur.com/maCWemy

**Comment by Serithul** [comment]
Done by source means healing done by the warrior not done to the warrior. Entirely different things.

**Comment by Serithul** [comment]
That screenshot shows that the training dummy was entirely healed by inspiring presence while the warrior was healed by leech and ignore pain. 99.1% healing done by inspiring aura, 99.1% healing done to the dummy. 0.8 % healing done from leech and 0.1% healing done from ignore pain, 0.9% healing done to the warrior. The math is right there and also the needed proof.
