### ISSUE TITLE
[Core] - Spell Flametongue - Enhancement Shaman Ability

### ISSUE THREAD

**Issue by axryn** [GuabinaCore/WoWKoi#86]
Ability: Flametongue
Class: Enhancement Shaman

https://www.wowhead.com/spell=193796/flametongue

Currently 50% functioning. Additional fire damage on melee attacks buff is active, but extra damage does not proc.

**Comment by bonfim97** [comment]
The extra dmg seems to only be proccing with off hand white hits while it should be applied by all weapon attacks, including main-hand hits and ALL weapon attacks wich include all spells that "require a mellee weapon", auto atacks and windury. 

Same goes for **Hailstorm** talent wich seems to work better since mh atack counts but not all special atacks seem to proc it.

"Note that this says WEAPON attacks. This talent encompass any spell which lists 'requires melee weapon' in the description. If you look at enhance's spells, that's actually most of them: rockbiter/boulderfist, windsong, crash lightning, flametongue, lava lash, sundering, stormstrike, and frostbrand itself (if you're reapplying it - initial spell doesn't proc the bonus damage) all fall under this category, as well as regular melee attacks (white swings). Each of these attacks procs a BONUS 35% damage spell added onto them, which critically strike. It's insane; this talent will pretty easily be on of your biggest sources of damage, since it's pretty much a straight 35% damage increase, proccing off of every single spell in your rotation (as well as your melee swings) with the exception of some a few spells, namely: feral lunge, lightning bolt, fury of air, lightning shield, feral spirit, and earthen spike. As of this writing (patch 7.1.22995), the talents listed are all suboptimal dps talents; this means that with an optimal rotation and allowing for good uptime, frostbrand will end up being something like 28-30% of your total damage.

This also means that in pvp, you're going to be hitting harder with each spell WHILE SLOWING YOUR ENEMY. That's absolutely crazy."
https://www.wowhead.com/spell=210853/hailstorm#comments

**Comment by Maczuga** [comment]
Just tested on training dummy - had 0 procs from either of weapons.

It procs on regular monsters tho, but only from offhand as mentioned earlier. Should proc from white attack from both main and off hand.

**Comment by Thordekk** [comment]
Chech database spell proc
